# Generated by Django 4.0.5 on 2022-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('desc', models.TextField()),
                ('price', models.CharField(max_length=256)),
                ('count', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
