# Generated by Django 4.0.5 on 2022-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
